### ISSUE TITLE
Allow for command links to be "materialized"

### ISSUE THREAD

**Issue by trajano** [adminfaces/admin-theme#100]
##### Issue Overview

In https://github.com/adminfaces/admin-theme/blob/master/src/main/resources/less/primefaces-admin/components/material.less it explicitly limits the material effect to `input` but ideally it should do it for anything that is `.ui-inputfield` that way we can add a class to commandLink of `ui-inputfield` so we can have a readonly like field link

##### Current Behaviour

An image may worth a thousand words

##### Expected Behaviour

An image may worth a thousand words

##### How to reproduce  

A sample xhtml code may help, ex:

```html
 <div class="ui-g-12 ui-md-4">
    <h1>OrderList</h1>
    <p:orderList value="#{orderListMB.cities}" var="city" controlsLocation="left" itemLabel="#{city}"
                 itemValue="#{city}" responsive="true">
        <f:facet name="caption">Cities List</f:facet>
    </p:orderList>
    </div>
</div>
```

##### Additional Information

* Affected version:  
* Browser version:

**Comment by rmpestano** [comment]
Hi @trajano,

do you have any sample code or image to show the behavior you are looking for?

I've search for "material" links in [materializecss](http://materializecss.com/forms.html) but did not found anything releated.

**Comment by trajano** [comment]
I have to do it on Monday.  I was also trying to do a disabled inputText but I need it to do an Ajax call when I click on the text before doing a show dialog.
