### ISSUE TITLE
Fa Stacked Icons does not work as expected

### ISSUE THREAD

**Issue by simeoreig** [adminfaces/admin-theme#101]
Fa stacked icons are badly located, if I change   <param-name>primefaces.THEME</param-name> to omega it works as expected.

##### Current Behaviour

with admin theme

![with](https://user-images.githubusercontent.com/22393668/30919548-016eb3bc-a3a2-11e7-98dc-fa511fdd901f.png)

##### Expected Behaviour

With omega theme

![without](https://user-images.githubusercontent.com/22393668/30919563-095ab12a-a3a2-11e7-9121-0584590db655.png)

##### How to reproduce  

```
<span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-twitter fa-stack-1x"></i>
</span>

```
##### Additional Information

        <dependency>
            <groupId>com.github.adminfaces</groupId>
            <artifactId>admin-theme</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <classifier>dev</classifier>
        </dependency>   

        <dependency>  
            <groupId>org.primefaces</groupId>  
            <artifactId>primefaces</artifactId>  
            <version>6.1.3</version>  
        </dependency>    
        

Many thanks!

**Comment by rmpestano** [comment]
Hi @simeoreig, 

can you try with [latest theme snapshot](https://github.com/adminfaces/admin-theme#8-snapshot)?

```
<dependency>
        <groupId>com.github.adminfaces</groupId>
        <artifactId>admin-theme</artifactId>
        <version>1.0.0-20170930.105314-1159</version>
        <classifier>dev</classifier>
    </dependency>   
```

**Comment by simeoreig** [comment]
It works!! 

As always, many many thanks for your job and your support

muito obrigado !! (many thanks in Brazilian)

**Comment by rmpestano** [comment]
de nada ;)
