### ISSUE TITLE
Enhance Editable Table Cell Background Colour

### ISSUE THREAD

**Issue by alissongodoi** [adminfaces/admin-theme#152]
Primefaces allows making table cells editable in order to dynamically change data. In the admin-theme, the colours in the background and the content of the selectable items are the same (blue).

Would that be possible to change the colour in the editable/selectable cell?

Examples at:
https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml
(Check the selectable columns Brand and Color in the admin theme)

##### Additional Information

* AdminFaces version:  1.0.0-RC12
* PrimeFaces version: Primefaces-6.1
* Browser version: Chrome

**Comment by rmpestano** [comment]
Just adding a screenshot of current editable so we can compare after the issue is implemented:

![datatable-editable-before](https://user-images.githubusercontent.com/1592273/39084279-67d6fd32-4549-11e8-8fdb-22deeb79529a.png)

Thank you for the feedback @alissongodoi

**Comment by alissongodoi** [comment]
It has been fixed properly fixed!
