### ISSUE TITLE
Question: Is it possible to set the skin per page basis?

### ISSUE THREAD

**Issue by mnesarco** [adminfaces/admin-theme#177]
##### Issue Overview

I want to use different skins based on the view, so some pages are skin-blue and another pages are skin-geen for example.

##### Current Behaviour

Current skins are somewhat session wide.

##### Expected Behaviour

If possible, have some view param to override the default skin in certain pages.

**Comment by rmpestano** [comment]
Hi, yes, just use the following snippet on your pages:

```
<h:form>
  <p:remoteCommand name="setSkinTeal" autoRun="true" action="#{skinMB.changeSkin('skin-teal')}" process="@this" update="@none" global="false"/>  
</h:form>

```

**Comment by rmpestano** [comment]
The above code will only take effect after a page reload. To make it change without a page refresh you'll also need to change the body class via javascript:

```
 function replaceSkinWith(newSkin) {
                                var cl = $('body').attr("class").split(" ");
                                for (var i = 0; i < cl.length; i++) { //removes current skin class from body
                                    if (cl[i].startsWith('skin-')) {
                                        $('body').removeClass(cl[i])
                                    }
                                }
                                $('body').addClass(newSkin);
}
```

**Comment by mnesarco** [comment]
Thanks @rmpestano , it is an ugly workaround but if it works I will use it by now.
I was thinking in something more elegant like:

<ui:param name="skin" value="skin-green" />

**Comment by rmpestano** [comment]
Also would work in preRenderView event but o likes your suggest, Will create anexo issue for It. Thanks

**Comment by rmpestano** [comment]
It is done on adminfaces/admin-template#90.

**Comment by mnesarco** [comment]
Hi @rmpestano, pretty nice. Thank you.
