### ISSUE TITLE
Icons not showing (both in my project, and on your showcase website)

### ISSUE THREAD

**Issue by SoarynAC** [adminfaces/admin-theme#209]
##### Issue Overview

For me the icons are not showing, neither in my project nor in your website.

##### Current Behaviour

The icons are simply not showing, when I go back to default theme they show, but with yours they don't

##### Expected Behaviour

They should show

##### How to reproduce  

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui" > 

<h:head>
</h:head> 
<h:body> 
	<p:button icon="ui-icon-plus"/>
</h:body> 
</html>

##### Additional Information

* AdminFaces version: 1.0.0-RC18
* PrimeFaces version: 6.2
* Browser version: Opera 55.0

**Comment by rmpestano** [comment]
please use[ font awesome icons](https://fontawesome.com/v4.7.0/icons/), e.g:

```
<p:button icon="fa fa-plus"/>

```

See an example at [admin-starter here](https://github.com/adminfaces/admin-starter/blob/494fdf9acd1606186103c620053672bad02d8ca8/src/main/webapp/includes/menubar.xhtml#L29).

I hope it helps.

**Comment by SoarynAC** [comment]
It still doesn't work, as I said, even when I visit your showcase website the icons are all missing.
I don't know if the problem is on your side, or mine.

**Comment by rmpestano** [comment]
Which browser are you using? Have you tried to clear your browser cache or use an anonymous window? 

Also, do you see any error on firebug? 

I'm using Opera 49.0.2725.64 and it looks ok here:

![opera](https://user-images.githubusercontent.com/1592273/45982322-befbc600-c02e-11e8-822d-69a9ed8ddf28.png)

Do you see the same issue on other browsers?

--

**Comment by SoarynAC** [comment]
Well, I did nothing, just refreshed the pages, but now everything is working fine, the icons load on my page and on your showcase website. The problem was on my side after all, sorry to bother you and thanks for the help!

**Comment by rmpestano** [comment]
No bother, glad it worked!
