### ISSUE TITLE
how to use template in Intellij

### ISSUE THREAD

**Issue by zubairfarooq13** [adminfaces/admin-theme#215]
I am unable to find the way, how to use this template in intelliJ . please guide me in easy steps. Thanks

**Comment by rmpestano** [comment]
Hi, please create another issue using the template (issue overview, current behavior, expected behavior etc...)

**Comment by zubairfarooq13** [comment]
I didn't understand, please explain how to ask question?

**Comment by rmpestano** [comment]
Just create a new issue and follow the issue template specifying your problem and steps to reproduce it.

For example I just don't know what problems are you having and how to reproduce It on my environment, without minimum information I can't help.

**Comment by zubairfarooq13** [comment]
I want to use adminLTE template for my project, but i am unable to use this template in my IDE. I am using IntelliJ.

**Comment by rmpestano** [comment]
Well the template doesn't depend on any particular IDE. 

Have you tried [admin-starter](http://github.com/adminfaces/admin-starter) project? I've used It on all major Java IDEs

**Comment by zubairfarooq13** [comment]
Yes,  i tried but i am stuck at command, i don't know where i have to execute command in wildfly. 

can you please help me.

**Comment by rmpestano** [comment]
If you're having trouble with IntelliJ, please open an issue on their [issue tracker here](https://youtrack.jetbrains.com/issues).


If you have problems with admin-template or admin-theme then I'll be able to help you.

**Comment by zubairfarooq13** [comment]
@rmpestano What is difference between admin-template and admin-theme?

**Comment by rmpestano** [comment]
Please look here https://adminfaces.github.io/site/

**Comment by zubairfarooq13** [comment]
I read this link carefully, i want to include adminfaces/admin-template in my IntelliJ project. 

Now, please tell me how to include because i don't know how to include

**Comment by zubairfarooq13** [comment]
@rmpestano Thanks for making video tutorial.. 
I am facing this issue, 

> **Error:** Artifact 'admin-starter:war exploded' has invalid extension

**Comment by zubairfarooq13** [comment]
@rmpestano i want to re-use JSF components, then adminlte-template will be used for this purpose?

**Comment by zubairfarooq13** [comment]
I executed AdminFaces-Starter successfully, but my goal is to re-use JSF components in web-designing. 
Please explain how can i do it?
