### ISSUE TITLE
Can't find a way to replace the default ajaxloadingbar.gif

### ISSUE THREAD

**Issue by danielemaddaluno** [adminfaces/admin-theme#218]
##### Issue Overview
I would like to change the default ajaxloadingbar.gif (it always shows me the gif from `primefaces-admin/images/ajaxloadingbar.gif`).

**Comment by rmpestano** [comment]
Hi @danielemaddaluno,

have you tried adding the following entry t `src/main/resources/admin-config.properties` file:

```
admin.loadingImage=myLoadingImage.png
``` 

the file must be under `webapp/resources/images` folder.

**Comment by danielemaddaluno** [comment]
Yeah it works perfectly!
Thank you again @rmpestano!
