### ISSUE TITLE
p:triStateCheckbox not working

### ISSUE THREAD

**Issue by martinmikula** [adminfaces/admin-theme#226]
##### Issue Overview

When i tried to use p:triStateCheckbox the closethick icon is not visible while button is focused.

##### How to reproduce  

Issue can be shown also on showcase page. Just click on tristate checkbox... Only two states working correctly...

##### Additional Information

* AdminFaces version:  1.0.0-RC20
* PrimeFaces version: 6.2
* Browser version: Chrome 71.0.3578.98 64bit

**Comment by rmpestano** [comment]
Hi @martinmikula, can you test again (you may need to clean browser caches)? it should be ok now. 

Thank you for reporting.
