### ISSUE TITLE
Style datatable rowExpansion

### ISSUE THREAD

**Issue by rmpestano** [adminfaces/admin-theme#232]
##### Issue Overview

Style DataTable [rowExpansion](https://www.primefaces.org/showcase/ui/data/datatable/expansion.xhtml)  

##### Current Behaviour

![row-expansion-before](https://user-images.githubusercontent.com/1592273/52952284-d97a6700-3362-11e9-9c55-da9c42e63245.png)

##### Expected Behaviour

 
![row-expansion-after](https://user-images.githubusercontent.com/1592273/52952291-df704800-3362-11e9-845c-bec2794aab12.png)

 
##### Additional Information

* AdminFaces version:  RC21
* PrimeFaces version:  
* Browser version:

**Comment by MNABIL89** [comment]
Same issue still with me
AdminFaces version: 1.0.2
PrimeFaces version: 7

**Comment by rmpestano** [comment]
Hi, can you reproduce on showcase here? https://adminfaces-adminfaces.apps.ca-central-1.starter.openshift-online.com/pages/components/datatable.xhtml

Also do you have a printscreen showing the issue? 

Thanks for the feedback
