### ISSUE TITLE
Asterisks for p:outputlabel / indicateRequired not working

### ISSUE THREAD

**Issue by jomu78** [adminfaces/admin-theme#235]
p:outputlabel indicateRequired controls whether an asterisk is shown for mandatory fields or not. The default value auto uses the for attribute to validate if the related input is mandatory or not. 

On Primefaces 6.2 without admin-theme / admin-template an asterisk is shown, if I use admin-theme it is not.  Even if I set indicateRequired="true" to the output label it does not show the asterisk. 

`
<p:outputLabel for="firstName" value="firstName />
<p:inputText id="firstName" value="#{view.firstName}" required="true" />
`

Am I doing something wrong or is this a bug?

##### Additional Information

* AdminFaces version: 1.0.0-RC21 
* PrimeFaces version:  6.2
* Browser version:  Chrome 72, Firefox  65

**Comment by rmpestano** [comment]
Hi @jomu78, it is removed on purpose, [see here](https://github.com/adminfaces/admin-theme/blob/9a7e42b8b5a30f8c5ce7430af7635a3ae7f4c8a1/src/main/resources/less/primefaces-admin/components/labels.less#L32).

You can bring them back by using a more specific css rule: 

----
 body .ui-outputlabel-rfi {
    display: inline;
}
---- 

Maybe we should make it configurable in admin template.

**Comment by rmpestano** [comment]
Just added the option to enable the asterisks via [admin-config.properties](https://adminfaces.github.io/site/docs/latest/#configuration) .

You'll need to [enable snapshots repository](https://github.com/adminfaces/admin-template#10-snapshots) and use admin-template 1.0.0-RC22-SNAPSHOT if you want to try it.

**Comment by jomu78** [comment]
tested, works for me

**Comment by rmpestano** [comment]
Thanks for the feedback.
