### ISSUE TITLE
The `SelectManyButton` widget doesn't display correctly in all cases

### ISSUE THREAD

**Issue by gestern** [adminfaces/admin-theme#241]
##### Issue Overview

Buttons are not displayed in the group. Instead, they are displayed as separate elements, which generally contradicts common sense, which was originally laid down. The [official documentation](https://www.primefaces.org/docs/guide/primefaces_user_guide_6_0.pdf) says:

>  3.118 `SelectManyButton`
> `SelectManyButton` is a multi select component using button UI.
> <img width="131" alt="image" src="https://user-images.githubusercontent.com/1861589/67164557-97d40d00-f384-11e9-85ce-3de2bd5e0762.png">

By the way, the following example of displaying this element is shown on the official AdminLTE [channel](https://adminlte.io/themes/AdminLTE/pages/UI/buttons.html):

<img width="178" alt="image" src="https://user-images.githubusercontent.com/1861589/67164712-4593eb80-f386-11e9-9cd5-dc3a4891c768.png">

and says:

> Horizontal button groups are easy to create with bootstrap. Just add your buttons inside `<div class="btn-group"></div>`

##### Current Behaviour

<img width="285" alt="image" src="https://user-images.githubusercontent.com/1861589/67164471-7cb4cd80-f383-11e9-939e-d5baf5615b57.png">

##### Expected Behaviour

<img width="279" alt="image" src="https://user-images.githubusercontent.com/1861589/67164649-732c6500-f385-11e9-983b-7f26c7e84d80.png">

Please do not pay attention to the alignment of the text (it may be any here and not essential).

##### How to reproduce  

You can simply repeat this example from official's [showcases](https://www.primefaces.org/showcase/ui/input/manyButton.xhtml):

```html
 <p:selectManyButton value="#{selectManyView.selectedOptions}">
            <f:selectItem itemLabel="b" itemValue="b" />
            <f:selectItem itemLabel="u" itemValue="u" />
            <f:selectItem itemLabel="i" itemValue="i" />
        </p:selectManyButton>
```

**Comment by rmpestano** [comment]
Hi, thank you for the opening the issue, I' ll have a look ASAP.

**Comment by rmpestano** [comment]
Hi @gestern, can you try with 1.0.3-SNAPSHOT with clean browser caches?

[See here]https://github.com/adminfaces/admin-theme#9-snapshot) on how to enable snapshots

**Comment by gestern** [comment]
<img width="196" alt="image" src="https://user-images.githubusercontent.com/1861589/68769507-1858f700-062d-11ea-8fdd-fdd843345c27.png">
Looks great
