### ISSUE TITLE
Fix tooltip z-index

### ISSUE THREAD

**Issue by gino0631** [adminfaces/admin-theme#248]
##### Issue Overview

A `p:tooltip` is behind pop-up elements.

##### Current Behaviour

Currently, theme.css sets a fixed value of 932 to a tooltip element:
```css
div.ui-tooltip {
    z-index: 932 !important;
}
```
As z-index of pop-up elements (`p:dialog`, `p:calendar`) is higher than 1000 and is incrementing, this makes `p:tooltip` invisible (behind the element).

##### Expected Behaviour

A `p:tooltip` staying always on top.

##### How to reproduce  

Check the tooltips over Previous and Next buttons of the pop-up calendar:
```html
<p:tooltip/>
<p:calendar ...></p:calendar>
```

The issue can be fixed by removing z-index declaration from tooltip.less, as it was done in #219 for other components.

##### Additional Information

* AdminFaces version: 1.2.0
* PrimeFaces version: 10.0.0
* Browser version: Google Chrome 88.0.4324.150

**Comment by rmpestano** [comment]
Thank you @gino0631, I'll starting to work on a new version that targets PrimeFaces 10 so if you find something else, please create issues.

**Comment by gino0631** [comment]
Just checked with PrimeFaces 8, and was able to reproduce the problem. The screenshot below shows the overridden z-index value:

![image](https://user-images.githubusercontent.com/13659309/115049802-c7b19180-9ee3-11eb-9c70-cecdd7b76843.png)
