### ISSUE TITLE
without-bootstrap classifier can not be used with 1.3.2

### ISSUE THREAD

**Issue by Mamezou-zhang-yong** [adminfaces/admin-theme#256]
##### Issue Overview

Got an error by using the following dependency , and the jar can not added into a project.

<dependency>
    <groupId>com.github.adminfaces</groupId>
    <artifactId>admin-theme</artifactId>
    <version>1.3.2</version>
    <classifier>without-bootstrap</classifier>
</dependency>

##### Current Behaviour

the without-bootstrap can not be added into project.

##### Expected Behaviour

admin-theme-1.3.2-without-bootstrap.jar should be added into project.

##### Additional Information

* AdminFaces version:  1.3.2
* PrimeFaces version: 11  
* Browser version:

**Comment by rmpestano** [comment]
Hi @Mamezou-zhang-yong, can you try with `v1.4.1`? Thank you for the feedback!

**Comment by Mamezou-zhang-yong** [comment]
@rmpestano sorry for the late reply. it is OK ,thanks.

**Comment by rmpestano** [comment]
👍
