### ISSUE TITLE
p:inputNumber not well showed

### ISSUE THREAD

**Issue by simeoreig** [adminfaces/admin-theme#30]
![inputnumber](https://cloud.githubusercontent.com/assets/22393668/25742457/daa0233a-318f-11e7-9d7a-3cf1a2003f63.png)

            <div class="container">

                <div class="col-lg-12">            

                    <div class="row">

                        <h3>Nova Factura</h3>

                        <div class="control-group form-group">
                            <div class="controls">
                                <label>Import Factura:</label>

                                <p:inputNumber styleClass="form-control" id="importfactura" value="#{controlFacturacio.facturaventa.importfactura}" symbol=" EUR" symbolPosition="s" 
                                               decimalSeparator="," thousandSeparator=".">  
                                </p:inputNumber>                                  
                            </div>
                        </div>

                    </div>

                </div>            
            </div>

**Comment by rmpestano** [comment]
Hi @simeoreig,

I think it is related to **form-control**  style class, same for #29. 

Can you try without it?

**Comment by simeoreig** [comment]
It works, thanks a lot  for help and theme

I thought bootstrap 3 supported input,textarea,checkbox,radio, select and all the HTML5 input types: text, password, datetime, datetime-local, date, month, time, week, number, email, url, search, tel, and color.

Therefore I wrongly thought p:calendar (datetime) and p:inputNumber (number) had to support  styleClass="form-control" to do it responsive and wide

I did the trick with a little css

![ok](https://cloud.githubusercontent.com/assets/22393668/25755407/3eac0294-31c3-11e7-8aae-94f360f20777.png)

**Comment by rmpestano** [comment]
> Therefore I wrongly thought p:calendar (datetime) and p:inputNumber (number) had to support styleClass="form-control" to do it responsive and wide

For Primefaces components be wide accordingly to the grid columns you can use **ui-fluid** class:

```
 <div class="col-lg-12 ui-fluid">            
```
