### ISSUE TITLE
Chip label misplaced

### ISSUE THREAD

**Issue by jsirach** [adminfaces/admin-theme#47]
Like said on Twitter, when an issue is found, i will create an account and file them. Keep up the good work, i really like the theme implementation!

I found the following:
When adding a chip the label is misplaced

![chip_error](https://cloud.githubusercontent.com/assets/29050343/26562783/0292e484-44ca-11e7-923b-776b18b43e91.png)

The below is what was expected

![chip_expected](https://cloud.githubusercontent.com/assets/29050343/26562793/0ff0416c-44ca-11e7-9173-ef8f999aa152.png)

This is fixed by overriding this in the admin template with:
`
span.ui-autocomplete-token-label {
    display: inline-block;
}
`
This currently is display: block.

Affected version: RC6
Browser: Chrome 58.0.3029.110 (Official Build) (64-bit)
OS: Windows 10

**Comment by rmpestano** [comment]
Hi @jsirach, 

Can you reproduce on [showcase chips sample](adminfaces-rpestano.rhcloud.com/showcase/pages/components/chips.xhtml)?

If no can you try clearing your browser cache? otherwise do you see any difference between showcase code and yours?

thank you very much for your collaboration!

**Comment by jsirach** [comment]
Hi @rmpestano 

Development is continuously with the developer tools open with cache disabled. But with shamefully updating primefaces from 6.1 RC3 to 6.1 in the pom the issue was solved (I noticed the css rule was different).

Thank you for your time, will pay better attention next time.

Cheers!

**Comment by rmpestano** [comment]
That's great news!  Yes, primefaces changed Chips CSS in the 6.1 release, glad It worked.
