### ISSUE TITLE
Dialog Framework don't respect modal

### ISSUE THREAD

**Issue by simeoreig** [adminfaces/admin-theme#68]
If we use nested dialogs like in (https://www.primefaces.org/showcase/ui/df/nested.xhtml) the second and next dialogs are not modal

**dialog open**

     Map<String, Object> options = new HashMap<>();
     options.put("modal", true);
     options.put("draggable", true);
     options.put("resizable", false);
     options.put("includeViewParams", true);

![dialogs](https://user-images.githubusercontent.com/22393668/27445753-48d22112-577b-11e7-98ae-1c7f909cd169.png)

If we change admin for omega, it works as it must do.

**web.xml**

    <context-param>
        <param-name>primefaces.THEME</param-name>
        
      <param-value>admin</param-value>        
    </context-param>

**pom.xml**

        <dependency>
            <groupId>com.github.adminfaces</groupId>
            <artifactId>admin-theme</artifactId>
            <version>1.0.0-RC6</version>
            <classifier>dev</classifier>
        </dependency>                     

        <dependency>  
            <groupId>org.primefaces</groupId>  
            <artifactId>primefaces</artifactId>  
            <version>6.1</version>  
        </dependency>

**Comment by rmpestano** [comment]
I'll have a look, thanks for reporting.

**Comment by rmpestano** [comment]
Hi @simeoreig,

Can you try with [latest SNAPSHOT](https://github.com/adminfaces/admin-theme#8-snapshot)? the version is 1.0.0-SNAPSHOT

**Comment by rmpestano** [comment]
Also I've put an example of dialog framework on showcase here: http://adminfaces-rpestano.rhcloud.com/showcase/pages/components/dialog.xhtml

**Comment by simeoreig** [comment]
It works, obrigado Rafael!

![itworks](https://user-images.githubusercontent.com/22393668/27489939-af403a8a-583c-11e7-84ab-4cd8afb3a8e3.png)
